### ISSUE TITLE
Stuck at loading screen of adobe . It freezes after that and i have to force close.

### ISSUE THREAD

**Issue by slaygun** [MiMillieuh/Photoshop-CC2022-Linux#106]
**Photoshop version**
CC2021

**Describe the bug**
when i launch the app the loading screen does appear but after some loading(mostly at initializing html surfaces) it gets stuck and i get prompted to wait or force quit again and again so i close it.

**System information**
- Distro : Ubuntu 22.04.2 LTS
- GPU : AMD
- WINE version : 8.0

**Log of command i tried to capture** it was too long so i shortened it
Script started on 2023-04-16 10:26:14+05:30 [TERM="xterm-256color" TTY="/dev/pts/7" COLUMNS="80" LINES="24"]
[?2004h]0;nabh@nitro: ~/Documents/Adobe/Adobe-Photoshop/drive_c[01;32mnabh@nitro[00m:[01;34m~/Documents/Adobe/Adobe-Photoshop/drive_c[00m$ sh launcher.shcript log.txt[10@h launcher.sh >[C[C[C[C[C[C[C[C
[?2004l
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
03ec:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
03ec:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
03ec:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\dvacrashhandler.dll", 000000000BC97E60) stub
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:nls:get_dummy_preferred_ui_language (0x8 0x4009 000000000011E134 0000000000000000 000000000011E130) returning a dummy value (current locale)
03ec:fixme:nls:get_dummy_preferred_ui_language (0x8 0x4009 000000000011E134 000000000BE54B50 000000000011E130) returning a dummy value (current locale)
03e8:fixme:reg:RegQueryInfoKeyW security argument not supported.
03ec:fixme:netprofm:list_manager_QueryInterface interface {00000126-0000-0000-c000-000000000046} not implemented
03ec:fixme:netprofm:connection_point_Advise 000000001569C8E0, 000000001569C7D0, 000000001569C7F0 - semi-stub
03ec:fixme:netprofm:connection_point_Advise 000000001569C950, 000000001569B990, 000000001569B9B0 - semi-stub
03ec:fixme:netprofm:list_manager_GetConnectivity 000000001569C8A0, 000000000011F280
03e8:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
03e8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
03ec:fixme:imm:ImeSetActiveContext (000000000006153A, 1): stub
03ec:fixme:imm:ImmReleaseContext (00000000000700D0, 000000000006153A): stub
03ec:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000017C715BD, 49) stub
[?25h03ec:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
03cc:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
02e0:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
04d8:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
04d4:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
[?25lr[?25h[?25lo[?25h0480:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
[?25lp[?25h[?25le[?25h[?25lr[?25h[?25lt[?25h[?25ly[?25h04d0:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
0478:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
[?25l[K[1C[?25h[?25lF[?25h[?25ll[?25h[?25la[?25h[?25lg[?25h[?25ls[?25h[?25l[K[1C[?25h[?25l=[?25h[?25l[K[1C[?25h[?25l0[?25h[?25lx[?25h[?25le[?25h

[?25li[?25h[?25ln[?25h[?25lf[?25h[?25lo[?25h[?25l:[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25lM[?25h[?25le[?25h[?25lm[?25h[?25lo[?25h[?25lr[?25h[?25ly[?25h03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
[?25l[K[1C[?25h[?25lT[?25h[?25ly[?25h[?25lp[?25h[?25le[?25h[?25l[[?25h[?25l0[?25h[?25l][?25h[?25l:[?25h03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
[?25l[K[1C[?25h[?25lP[?25h[?25lr[?25h[?25lo[?25h[?25lp[?25h[?25le[?25h[?25lr[?25h[?25lt[?25h[?25ly[?25h[?25l[K[1C[?25h[?25lF[?25h[?25ll[?25h[?25la[?25h[?25lg[?25h[?25ls[?25h[?25l[K[1C[?25h[?25l=[?25h[?25l[K[1C[?25h[?25l0[?25h[?25lx[?25h[?25l1[?25h

[?25li[?25h[?25ln[?25h[?25lf[?25h[?25lo[?25h[?25l:[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h[?25l[K[1C[?25h03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
[?25l[K[1C[?25h03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
[?25l[K[1C[?25h03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
03ec:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
[?25lM[?25h[?25le[?25h[?25lm[?25h[?25lo[?25h[?25lr[?25h[?25ly[?25h[?25l[K[1C[?25h[?25lT[?25h[?25ly[?25h[?25lp[?25h[?25le[?25h[?25l[[?25h[?25l1[?25h[?25l][?25h[?25l:[?25h[?25l[K[1C[?25h[?25lP[?25h[?25lr[?25h[?25lo[?25h[?25lp[?25h[?25le[?25h[?25lr[?25h[?25lt[?25h[?25ly[?25h[?25l[K[1C[?25h[?25lF[?25h[?25ll[?25h[?25la[?25h[?25lg[?25h[?25ls[?25h[?25l[K[1C[?25h[?25l=[?25h[?25l[K[1C[?25h[?25l0[?25h[?25lx[?25h[?25l1[?25h

03d0:fixme:system:QueryDisplayConfig (00000002 000000000011B33C 000000000143B660 000000000011B3A0 000000000143B700 0000000000000000): semi-stub
03d0:fixme:system:QueryDisplayConfig (00000002 000000000011B33C 000000000143B660 000000000011B3A0 000000000143B700 0000000000000000): semi-stub

**Comment by MiMillieuh** [comment]
Have you installed wine from the Ubuntu repository or winehq ?

**Comment by slaygun** [comment]
> Have you installed wine from the Ubuntu repository or winehq ?

winehq

**Comment by MiMillieuh** [comment]
Could you try using the devel branch ? Sometimes wine's stable branch has some missing things

**Comment by slaygun** [comment]
steps i performed-
sudo apt-get remove --purge wine-stable
sudo apt-get autoremove
sudo apt install --install-recommends winehq-devel
sudo apt update

nabh@nitro:~/Documents/Adobe/Adobe-Photoshop/drive_c$ sh launcher.sh
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine client error:0: version mismatch 758/762.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?

what do i do?

**Comment by slaygun** [comment]
it shows wine version  8.6 now

**Comment by MiMillieuh** [comment]
Are you sure the path you mentioned to the installer is correct ? 

`/Documents/Adobe/Adobe-Photoshop/`

It seems to be at root and in document ? 

Photoshop cannot be executed as root

**Comment by slaygun** [comment]
not in root.
this is the path of launcher.sh
/home/nabh/Documents/Adobe/Adobe-Photoshop/drive_c

**Comment by MiMillieuh** [comment]
Do you have the OSS driver ?

**Comment by slaygun** [comment]
how do i check

**Comment by MiMillieuh** [comment]
Well if you have installed AMD-GPU drivers or if you have the kernel ones

**Comment by slaygun** [comment]
no i have not

**Comment by MiMillieuh** [comment]
If your DE crashes maybe it's related to something else... maybe you can try to disable window decoration in winecfg

**Comment by slaygun** [comment]
im using gnome tried gnome and xorg both btw.
also doing what u told didnt work.

**Comment by MiMillieuh** [comment]
Well that's a weird issue then... I can't really explain why your DE crashes when you launch PS to be fair. maybe an extension ? 

To be honest I'm not really sure about how and why this issue happen so I'm sorry if I told you to try things that aren't working. I'm trying to be logic but well I'm not really ;-;

**Comment by slaygun** [comment]
its fine you know it was working with lutris somehow but i reinstalled it and it stopped working bc of some windows update thing. have to try again with wine 8.0.1 version

**Comment by MiMillieuh** [comment]
Maybe you could just try to use the latest wine, it works.

**Comment by MiMillieuh** [comment]
I don't know... I'm working on making a wine build that's shiped with it like with illustrator (thought it doesn't really need modification unlike illustrator...) so maybe it will be fixed... but that's kinda strange to be honest that lutris managed to fix it... maybe a missing library that lutris provide with it's runtime...

It everything is fine I'll let you close the issue.

**Comment by slaygun** [comment]
yeah lutris is using some custom lutris ge proton so maybe that fixed it.  
ig for now its fine
