### ISSUE TITLE
allredist/setup_vkd3d_proton.sh: 78: Bad substitution

### ISSUE THREAD

**Issue by artik** [MiMillieuh/Photoshop-CC2022-Linux#23]
Thank your so much for your efforts, and I'm pretty sure I'm close to the goal.

The installation script for CC2021 worked, but I don't have GPU acceleration.
When I look at the logs, at the end of the installation I have this error:

`allredist/setup_vkd3d_proton.sh: 78: Bad substitution`

So I tried to re-download `allredist.tar.gz`, extract it, and manually launch it, but same error.
Do you know how to fix that ?

**Comment by artik** [comment]
I manage to be able to install it changing

`WINEPREFIX=/home/artik/photo/Adobe-Photoshop sh allredist/setup_vkd3d_proton.sh install`
by
`WINEPREFIX=/home/artik/photo/Adobe-Photoshop ./allredist/setup_vkd3d_proton.sh install`

Anyway to fix it in your script to make it finishing it properly ?

**Comment by MiMillieuh** [comment]
> I manage to be able to install it changing
> 
> `WINEPREFIX=/home/artik/photo/Adobe-Photoshop sh allredist/setup_vkd3d_proton.sh install`
> by
> `WINEPREFIX=/home/artik/photo/Adobe-Photoshop ./allredist/setup_vkd3d_proton.sh install`

Hello,

That's strange because the vkd3d setup is a sh file so you shouldn't get this issue... 

Maybe can I know more about what you're using (distro, shell, de, kernel)

**Comment by artik** [comment]
Here you are:
```
System:    Host: linuxmint Kernel: 5.13.0-44-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
           Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
```
As shell I'm using `/bin/bash`

**Comment by MiMillieuh** [comment]
Still a mystery x) 

I'll use winetricks now as it can ship VKD3D now.

So the issue should be fixed in the next update

**Comment by MiMillieuh** [comment]
Fixed
