### ISSUE TITLE
After installing Photoshop 2022 with gui installer, it does not have an icon in the app list

### ISSUE THREAD

**Issue by Lekrixsss** [MiMillieuh/Photoshop-CC2022-Linux#28]
You need to change 94 line in it's installing script from
`mv allredist/photoshop.png ~/.local/share/icons`
to
`mv allredist/photoshop.png ~/.local/share/icons/photoshop.png`

**Comment by MiMillieuh** [comment]
This one is distro specific... however on my distro both work so I'll put the file name after
