### ISSUE TITLE
appmenu-gtk-module on fedora

### ISSUE THREAD

**Issue by Lekrixsss** [MiMillieuh/Photoshop-CC2022-Linux#30]
Hello, I see you use fedora on you screenshots, but I haven't found appmenu-gtk-module(which is in requirements for your script) for fedora, how can I install it?

**Comment by MiMillieuh** [comment]
Hello, 
It's not really necessary but a recommendation. it's used by a gnome extension to display wine tray in the tray icon but if you prefer not you'll just have a wine tray window that will open sometimes.

You should be able to run without
