### ISSUE TITLE
3DL and CUBE files not loading in color lookup

### ISSUE THREAD

**Issue by TheBeeBoi** [MiMillieuh/Photoshop-CC2022-Linux#39]
**Photoshop version**
CC2021

**Describe the bug**
I was making a night scenery with photoshop, so I used Moonlight.3DL, but as soon as I chose it, 

**To Reproduce**
1. Open any png file
2. Add a color lookup to the background layer
3. Choose any 3DL or CUBE file
4. Photoshop freezes

**Expected behavior**
For the color lookup to work.

**System information**
- Distro : MX Linux (Debian 11 - No systemd)
- GPU : Intel i3 10th generation iGPU

**Missing information**
(None yet)

**Comment by MiMillieuh** [comment]
Hello, 

I never used moonlight. I guess  I don't even know it that's a plug-in. If that's the case, I don't think I'll be able to help. 

However I see that you have a weak GPU. So maybe you should check if you have the gpu acceleration in the setting and if it's enabled. 

If it is you can also try without. 
But it shouldn't affect.

**Comment by TheBeeBoi** [comment]
> Hello,
> 
> I never used moonlight. I guess I don't even know it that's a plug-in. If that's the case, I don't think I'll be able to help.
> 
> However I see that you have a weak GPU. So maybe you should check if you have the gpu acceleration in the setting and if it's enabled.
> 
> If it is you can also try without. But it shouldn't affect.

It's not a plugin...
It's a color lookup.

**Comment by TheBeeBoi** [comment]
> u have the gpu acceleration in the setting an

It's enabled.
I'll try disabling it
