### ISSUE TITLE
PS 2021 crashes opening menu

### ISSUE THREAD

**Issue by Vinchester1986** [MiMillieuh/Photoshop-CC2022-Linux#42]
Hi, I'm using Ubuntu 22.04 + Wine 7.11 Staging + PS 2021. Everything works except main app menu (File, Edit, Image, etc). App simply crashes when I'm trying to open every menu item while shortcuts opening same items are working fine.

**Comment by MiMillieuh** [comment]
> Hi, I'm using Ubuntu 22.04 + Wine 7.11 Staging + PS 2021. Everything works except main app menu (File, Edit, Image, etc). App simply crashes when I'm trying to open every menu item while shortcuts opening same items are working fine.

Hello,

I never encountered this issue...
Although I'll recommend to try with wine-devel as staging patches caused some problems in the past.

**Comment by Vinchester1986** [comment]
Updated to dev version and it works now. Thx in advance, great job.

**Comment by MiMillieuh** [comment]
> Updated to dev version and it works now. Thx in advance, great job.

Glad it worked.

**Comment by fdev988** [comment]
@Vinchester1986 what do you mean by dev version?

**Comment by MiMillieuh** [comment]
> @Vinchester1986 what do you mean by dev version?
> 
> EDIT:
> Oh you mean wine-dev version, well then **how do I install wine-devel on archlinux? I can only find wine-staging and wine-stable in the repos**

Just use wine stable then...

The devel version is ahead but not as stable as the stable one.

Staging follow the devel version but has some patches that aren't compatible with my custom version of photoshop.

I recommend to use devel but stable should do the trick.

**Comment by Vinchester1986** [comment]
Yeah, you're right, wine-devel. I'm using Ubuntu 22.04 not Arch as I mentioned in start post. I've faced another problem though - PS launches only once when booting system, after closing PS it doesn't launch and I need to reboot. Not a big issue for me, but maybe you could fix it. Thx in advance.

**Comment by MiMillieuh** [comment]
> Yeah, you're right, wine-devel. I'm using Ubuntu 22.04 not Arch as I mentioned in start post. I've faced another problem though - PS launches only once when booting system, after closing PS it doesn't launch and I need to reboot. Not a big issue for me, but maybe you could fix it. Thx in advance.  

I don't face this issue but you might be able to kill photoshop or any adobe services running to be able to run photoshop again. I've already encountered this issue with InDesign and killing some adobe processes manually do the trick.

**Comment by YoungFellow-le** [comment]
> @Vinchester1986 what do you mean by dev version?
> 
> EDIT: Oh you mean wine-dev version, well then **how do I install wine-devel on archlinux? I can only find wine-staging and wine-stable in the repos**

The `wine` package is the devel version in the arch repo (`sudo pacman -S wine`)

> Staging follow the devel version but has some patches that aren't compatible with my custom version of photoshop.

I've used wine staging and faced no issues.

**Comment by Vinchester1986** [comment]
> > Yeah, you're right, wine-devel. I'm using Ubuntu 22.04 not Arch as I mentioned in start post. I've faced another problem though - PS launches only once when booting system, after closing PS it doesn't launch and I need to reboot. Not a big issue for me, but maybe you could fix it. Thx in advance.
> 
> I don't face this issue but you might be able to kill photoshop or any adobe services running to be able to run photoshop again. I've already encountered this issue with InDesign and killing some adobe processes manually do the trick.

I killed adobe + wine processes and It helped - I can launch PS without rebooting system. Thx for advice.

**Comment by Vinchester1986** [comment]
> 
> I don't face this issue but you might be able to kill photoshop or any adobe services running to be able to run photoshop again. I've already encountered this issue with InDesign and killing some adobe processes manually do the trick.

I killed adobe + wine processes and It helped - I can launch PS without rebooting system. Thx for advice.
