### ISSUE TITLE
Photoshop 2021 crash with wine >=7.10

### ISSUE THREAD

**Issue by Lekrixsss** [MiMillieuh/Photoshop-CC2022-Linux#43]
**Photoshop version**
CC2021

**Describe the bug**
Photoshop 2021 crash with wine >=7.10

**To Reproduce**
1. Use wine >=7.10
2. Start Photoshop
3. Photoshop/wine crash

**Expected behavior**
Photoshop work

**System informations**
- Distro : Arch
- GPU : NVIDIA

**Comment by MiMillieuh** [comment]
Not reproduced... need more information

**Comment by Lekrixsss** [comment]
After latest arch update it broke down, so I moved to fedora, can't reproduce this on fedora

**Comment by MiMillieuh** [comment]
If you use staging, that's the reason.

**Comment by Whax** [comment]
@Lekrixsss 
You was probably with wine-staging like MiMillieuh said. I had the same problem. With wine 7.13 (Not staging) all is working fine with an Arch Linux up to date and nvidia-lts drivers. But have fun with Fedora :3 

@MiMillieuh 
Thanks a lot for your work, it's very pleasant to have Photoshop installed with a single script :)

**Comment by MiMillieuh** [comment]
> @Lekrixsss 
> You was probably with wine-staging like MiMillieuh said. I had the same problem. With wine 7.13 (Not staging) all is working fine with an Arch Linux up to date and nvidia-lts drivers. But have fun with Fedora :3 
> 
> @MiMillieuh 
> Thanks a lot for your work, it's very pleasant to have Photoshop installed with a single script :) 
> 
> 

Glad it worked for you ^^
