### ISSUE TITLE
Photoshop hangs when opening any menu

### ISSUE THREAD

**Issue by NdranC** [MiMillieuh/Photoshop-CC2022-Linux#45]
**Photoshop version**
CC2021

**Describe the bug**
After install, if you try to open any menu item like File, Edit, etc. The menu will open properly but photoshop will hang. I also experience a certain degree of side effects on the rest of my computer until I force kill photoshop through the terminal.

**To Reproduce**
1. Launch Photoshop CC2021
2. Click on "File" to open the menu
3. Program hangs unable to close it or click on anything

**Screenshots**

This is the terminal output of Photoshop once I've triggered the hang.

078c:err:sync:RtlpWaitForCriticalSection section 000000014C893808 "?" wait timed out in thread 078c, blocked by 0660, retrying (60 sec)
m Files\Adobe\Adobe Photoshop 2021\photoshop.exe: ../wine-staging/dlls/ntdll/unix/thread.c:1740: ntdll_set_exception_jmp_buf: Assertion `!jmp || !ntdll_get_thread_data()->jmp_buf' failed.
017c:fixme:win:DisableProcessWindowsGhosting : stub
0188:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0188:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0188:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
0190:fixme:thread:QueryThreadCycleTime (000000000000015C,0000000003B5FAF0): stub!
0188:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
info:  Game: Adobe Spaces Helper.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10:
info:    Driver: 22.1.3
info:    Vulkan: 1.3.211
info:    Memory Heap[0]:
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:    Memory Heap[1]:
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:    Memory Heap[2]:
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
392:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
392:info:vkd3d_instance_init: vkd3d-proton - build: cafe99e223296e2.
392:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
392:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 3584, may be inaccurate.
info:  Game: Adobe Spaces Helper.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10:
info:    Driver: 22.1.3
info:    Vulkan: 1.3.211
info:    Memory Heap[0]:
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:    Memory Heap[1]:
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:    Memory Heap[2]:
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
392:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
392:info:vkd3d_instance_init: vkd3d-proton - build: cafe99e223296e2.
392:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutable_descriptor_type.
392:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 3584, may be inaccurate.

**System informations**
- Distro : Arch Linux
- GPU : AMD (Open Source Drivers)

**Additional context**
I recently switched from fedora where this problem did not occur. My photoshop installation on fedora was about 5 months ago so it's possible this bug is recent.

**Comment by NdranC** [comment]
Crap, yeah I was using wine-staging. Is this a recent problem or has this always been the case?

Regardless, installing the latest wine in the arch repos fixed the issue as far as I can tell.

**Comment by ngxson** [comment]
I have the same problem with wine 7.2 (stable version, installed with `sudo dnf install wine`).

Can you please reopen the issue?

```
0564:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
06a0:fixme:thread:QueryThreadCycleTime (0000000000000134,0000000003BAFAF0): stub!
0564:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0570:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
0570:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
06b8:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
06b8:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
06b8:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
06b8:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: Adobe Spaces Helper.exe
info:  DXVK: v1.10.2
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
i06b8:fixme:system:EnableNonClientDpiScaling (000000000008004C): stub
nfo: 06b8:fixme:dwmapi:DwmExtendFrameIntoClientArea (0000000000070046, 000000000011B6A0) stub
 OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
06b8:fixme:win:GetPointerType (0 000000000011CCFC): stub
info06b8:fixme:dwmapi:DwmExtendFrameIntoClientArea (0000000000070046, 000000000011DEE0) stub
:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:06b8:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000067C515A8, 43) stub
    VK_KH06e0:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
R_surface
info:    VK06e0:fixme:wbemprox:client_security_SetBlanket 00000002419BFE40, 000000004ADF60C0, 10, 0, (null), 3, 3, 0000000000000000, 0
06e0:fixme:wbemprox:client_security_Release 00000002419BFE40
_KHR_win32_surface
warn:  Skipping CPU adapter: llvmpipe (LLVM 14.0.0, 256 bits)
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11C06b8:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DCD0 1 C) semi-stub
oreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Device properties:
info:    Device name:     : AMD RADV RAVEN
info:    Driver version   : 22.1.4
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_4444_formats
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    indep06b8:fixme:ole:CoResumeClassObjects stub
endentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy06ac:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
                      : 1
info:  06ac:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
  textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 1
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_buffer_device_address
info:    bufferDeviceAddress                    : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:  DXVK: Read 0 valid state cache entries
info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  0570:fixme:thread:QueryThreadCycleTime (FFFFFFFFFFFFFFFE,000000000011E930): stub!
f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f06ac:fixme:thread:QueryThreadCycleTime (FFFFFFFFFFFFFFFE,000000000011E930): stub!
8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
0564:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x70076
err:   Failed to create surface
050c:fixme:file:ReplaceFileW Ignoring flags 2
06b8:fixme:process:GetProcessMitigationPolicy (FFFFFFFFFFFFFFFF, 4, 000000000011D7B8, 4): stub
04fc:fixme:file:ReplaceFileW Ignoring flags 2
04b0:err:sync:RtlpWaitForCriticalSection section 000000014C893808 "?" wait timed out in thread 04b0, blocked by 06b8, retrying (60 sec)
m Files\Adobe\Adobe Photoshop 2021\photoshop.exe: dlls/ntdll/unix/thread.c:1740: ntdll_set_exception_jmp_buf: Assertion `!jmp || !ntdll_get_thread_data()->jmp_buf' failed.
0244:fixme:win:DisableProcessWindowsGhosting : stub
02f8:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
015c:fixme:thread:QueryThreadCycleTime (0000000000000134,0000000003BAFAF0): stub!
02f8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
760:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
760:info:vkd3d_instance_init: vkd3d-proton - build: cafe99e223296e2.
760:fixme:d3d12_find_physical_device: Could not find Vulkan physical device for 
DXGI adapter.
760:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutab
le_descriptor_type.
760:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 640, may be 
inaccurate.
760:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
760:info:vkd3d_instance_init: vkd3d-proton - build: cafe99e223296e2.
760:fixme:d3d12_find_physical_device: Could not find Vulkan physical device for 
DXGI adapter.
760:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_VALVE_mutab
le_descriptor_type.
760:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 640, may be 
inaccurate.
0244:fixme:dbghelp_dwarf:dwarf2_get_cie wrong CIE pointer at 0 from FDE 25f4
0244:fixme:dbghelp_dwarf:dwarf2_get_cie wrong CIE pointer at 0 from FDE 25f4
01fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E010 1 C) semi-stub
01fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DED0 1 C) semi-stub
01fc:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
01fc:fixme:wbemprox:client_security_SetBlanket 00000002419BFE40, 0000000000FA3670, 10, 0, (null), 3, 3, 0000000000000000, 0
01fc:fixme:wbemprox:client_security_Release 00000002419BFE40
01fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DDB0 1 C) semi-stub
01fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DB80 1 C) semi-stub
01fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DAE0 1 C) semi-stub

```

**Comment by MiMillieuh** [comment]
You should use : 

`dnf install winehq-stable` or `dnf install winehq-devel`

Wine alone doesn't install everything

**Comment by ngxson** [comment]
Thank you. It fixed the problem.

No for anybody having the same problem: `winehq-stable` is not present in WineHQ repo for fedora 36. Use 35 instead:
`dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/35/winehq.repo`

**Comment by NeuHix** [comment]
Would I've to remove my current version of wine which is `wine-7.12 (Staging)` . ?
On  `sudo dnf install winehq-stable`  I get [this](https://pastebin.com/cXd3vK5u) .
And removing the current wine installed on my pc,  would it cause any error to **already installed Photoshop**  ?
So installing stable wine would fix the **menu crashing problem.** Right?

**Comment by MiMillieuh** [comment]
> Would I've to remove my current version of wine which is `wine-7.12 (Staging)` . ?
> On  `sudo dnf install winehq-stable`  I get [this](https://pastebin.com/cXd3vK5u) .
> And removing the current wine installed on my pc,  would it cause any error to **already installed Photoshop**  ?
> So installing stable wine would fix the **menu crashing problem.** Right?

It's supposed to... staging patches have some issues with photoshop and the stable is sometimes not upstream enough depending on your distro. I recommend to use wine-devel

**Comment by ngxson** [comment]
Alternative method is to use proton from steam. I'm using proton 6.3 and it works fine.

```
#!/usr/bin/env bash
export SCR_PATH="pspath"
export CACHE_PATH="pscache"
export RESOURCES_PATH="$SCR_PATH/resources"
export WINE_PREFIX="$SCR_PATH/prefix"
export FILE_PATH=$(winepath -w "$1")
export WINEPREFIX="/home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop"
export DXVK_LOG_PATH=/home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop
export DXVK_STATE_CACHE_PATH=/home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop

export LD_PRELOAD=""
export W="/home/YOUR_USERNAME/.local/share/Steam/steamapps/common/Proton 6.3/dist"
export WINEVERPATH=$W
export PATH=$W/bin:$PATH
export WINESERVER=$W/bin/wineserver
export WINELOADER=$W/bin/wine
export WINEDLLPATH=$W/lib/wine/fakedlls
export LD_LIBRARY_PATH="$W/lib:$LD_LIBRARY_PATH"
export PROTON_USE_WINED3D=1

export SteamAppId="photoshop.exe"

"$WINELOADER" /home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop/drive_c/Program\ Files/Adobe/Adobe\ Photoshop\ 2021/photoshop.exe $FILE_PATH
```

**Comment by MiMillieuh** [comment]
> Alternative method is to use proton from steam. I'm using proton 6.3 and it works fine.
> 
> ```
> #!/usr/bin/env bash
> export SCR_PATH="pspath"
> export CACHE_PATH="pscache"
> export RESOURCES_PATH="$SCR_PATH/resources"
> export WINE_PREFIX="$SCR_PATH/prefix"
> export FILE_PATH=$(winepath -w "$1")
> export WINEPREFIX="/home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop"
> export DXVK_LOG_PATH=/home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop
> export DXVK_STATE_CACHE_PATH=/home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop
> 
> export LD_PRELOAD=""
> export W="/home/YOUR_USERNAME/.local/share/Steam/steamapps/common/Proton 6.3/dist"
> export WINEVERPATH=$W
> export PATH=$W/bin:$PATH
> export WINESERVER=$W/bin/wineserver
> export WINELOADER=$W/bin/wine
> export WINEDLLPATH=$W/lib/wine/fakedlls
> export LD_LIBRARY_PATH="$W/lib:$LD_LIBRARY_PATH"
> export PROTON_USE_WINED3D=1
> 
> export SteamAppId="photoshop.exe"
> 
> "$WINELOADER" /home/YOUR_USERNAME/programs/photoshop/Adobe-Photoshop/drive_c/Program\ Files/Adobe/Adobe\ Photoshop\ 2021/photoshop.exe $FILE_PATH
> ```

It's nice that it works but I woulde really recommend it. Vanilla wine is way more easier to control
