### ISSUE TITLE
Stuck on installation at 70% 

### ISSUE THREAD

**Issue by AmmarHaddadi** [MiMillieuh/Photoshop-CC2022-Linux#47]
**Bug Description**
I have no Idea why , but the installation is stuck on 70% for like 40 mins
I relaunched the installer but it still stuck

**To Reproduce**
1. Go to the folder 
2. Open terminal there and write "./Bin/ps-installer" since the executable was not working for me
3. Wait for ever on 70%

**Screenshots**
![image](https://user-images.githubusercontent.com/75220043/178828915-dc911c2d-06b8-45fe-a5e4-d0c57dbffc15.png)
edit :
![image](https://user-images.githubusercontent.com/75220043/178830643-569aa928-21c8-42fb-8d7b-c7ff2736eae7.png)
end of edit 

**System informations**
- Distro : Manjaro KDE (Up to date 7/13/2022)
- Installing directory : ~/apps/Photoshop (basically the home directory

**Comment by MiMillieuh** [comment]
This is common on some distribution...
You should use the CLI installer instead. 
I don't really know why this happened since the same script is used...

**Comment by AmmarHaddadi** [comment]
I think we should accept the fact that it doesn't work on all Distros
