### ISSUE TITLE
Photoshop script needs to be rewritten a little to actually work

### ISSUE THREAD

**Issue by fislysandi** [MiMillieuh/Photoshop-CC2022-Linux#50]
**Photoshop version**
eg : CC2021
Wine latest version

**Describe the bug**
wine fails to launch wineboot and load kernel32.dll
**To Reproduce**
1.install photoshop by installer.sh
2.launch photoshop
3.get nothing
4.after a short period of time softlocks the pc (in my case virtualmachine)

**Screenshots**
![vmware_fJElRtvZeX](https://user-images.githubusercontent.com/45166203/178845919-211b9982-3427-4de3-9ab9-a5c32163695e.jpg)

**Expected behavior**
for photoshop to launch

**System informations**
- Distro : Arch_Linux
- GPU : (NVIDIA)

**Additional context**
This is a fresh install from arch titus script i just installed wine and winetricks.
i use GTX 1060 8 GB
and i have a intel CPU

found out i was using wine staging will try the aur wine-stable package soon.

**Comment by fislysandi** [comment]
ok update on the issue i used the wine stable and still got the same issue 

also seems like there is a bug in your script seems like 
you forgot to export the WINEPREFIX= and from that issues arise
well this photoshop script will not work untill you fix the script
if i export it manually it does not give me the wineboot issue but still softlocks the virt machine

sagde i really wanna see this script to succeed.

**Comment by fislysandi** [comment]
This is what happens when you try to open it up
![Uploading vmware_vcV0u0TFLp.png…]()

**Comment by fislysandi** [comment]
this install script works perfectly fine for me. https://github.com/Gictorbit/photoshopCClinux

so i guess i have to wait and see.

**Comment by MiMillieuh** [comment]
Please use the installer in the release section.

**Comment by fislysandi** [comment]
well thanks will try that later.

**Comment by MiMillieuh** [comment]
You should also know that if your device don't support vulkan it won't work.
I don't know if VMware supports vulkan.

**Comment by fislysandi** [comment]
(*going a little off topic*)
if i ever would learn bash scripting i would write a script that would install *EVERYTHING* that a 3d artist needs/uses on windows

things that are native 
(Maya) (Short Explanation: this is where 3d artists rig and do animation) ( im just having libcrypt issues that i need to fix),

pureref (Short Explanation: this a massive refrence board where artists can yeet their refrences to)(would like to use beeref(FOSS on python(The Project is Abandoned)) but the pkg is broken),

Blender (Short Explanation:the most powerful 3d software to exist/can be used not just for 3d) (its native and its going to be way faster since its built for linux)

Adobe Substance Painter(Short Explanation: this is where artists make their textures) (you can download it Through AUR)

windows only apps that run almost natively (sometimes faster on linux)
 
(Zbrush) (Short Explanation: this is where 3d artists sculpt things) needs one dll override in order for your viewport to not go batshit insane, and emulate desktop to make wintab(aka pen pressure to work)

(Marmoset toolbag) (short explanation: this is where 3d artists bake normals and render their final work) installs natively you just need to make sure that you enable DXVK/VKD3D and after that its just native performance

(RizomUV) (Short Explanaiton: this is where 3d artists unwrap their meshes) literally windows experience in terms of installation click install and it just works.

i would make a script that install all of the above and include your script as an option if you like REALLY need photoshop instead i would just install krita,gimp is kinda not my taste for me.

**Comment by MiMillieuh** [comment]
> (_going a little off topic_) if i ever would learn bash scripting i would write a script that would install _EVERYTHING_ that a 3d artist needs/uses on windows
> 
> things that are native (Maya) (Short Explanation: this is where 3d artists rig and do animation) ( im just having libcrypt issues that i need to fix), it exists on AUR but the build of adsklicensing fails so you have to do it the scuffed way.
> 
> pureref (Short Explanation: this a massive refrence board where artists can yeet their refrences to)(would like to use beeref(FOSS on python(The Project is Abandoned)) but the pkg is broken),
> 
> Blender (Short Explanation:the most powerful 3d software to exist/can be used not just for 3d) (its native and its going to be way faster since its built for linux)
> 
> Adobe Substance Painter(Short Explanation: this is where artists make their textures) (you can download it Through AUR)
> 
> windows only apps that run almost natively (sometimes faster on linux)
> 
> (Zbrush) (Short Explanation: this is where 3d artists sculpt things) needs one dll override in order for your viewport to not go batshit insane, and emulate desktop to make wintab(aka pen pressure to work)
> 
> (Marmoset toolbag) (short explanation: this is where 3d artists bake normals and render their final work) installs natively you just need to make sure that you enable DXVK/VKD3D and after that its just native performance
> 
> (RizomUV) (Short Explanaiton: this is where 3d artists unwrap their meshes) literally windows experience in terms of installation click install and it just works.
> 
> i would make a script that install all of the above and include your script as an option if you like REALLY need photoshop instead i would just install krita,
> 
> gimp is meh.

As long as I'm credited for photoshop, I'm ok with it.

**Comment by fislysandi** [comment]
hey noob question, i booted into my hard drive installation of arch and uhh how do i give read and write permissions the entire home drive?

i genuinely want to know that.

**Comment by MiMillieuh** [comment]
> hey noob question, i booted into my hard drive installation of arch and uhh how do i give read and write permissions the entire home drive?
> 
> i genuinely want to know that.

With the chown command... but it isn't recommended to give you permission in the home folder... but in your personal folder 

Ex : don't give permission to /home/
But to /home/username/

**Comment by fislysandi** [comment]
hey seems like you did a big mistake writing a script since $1 variable leads to a filename not a path to user and it tries to write to root. 

you should use $HOME variable instead since it will actually use the /home/user/ path to make the script somewhat work for some reason wget winetricks stops working for no reason

i also added 2 lines to specify script path variable 
at the begginning of the script
so you can invoke it at any time you want.

i will upload my modified sh script here 


hopefully you are much more skilled at bash scripting and fix the issue

**Comment by MiMillieuh** [comment]
The simple answer at why it isn't working it's because you havent read the documentation.
as you say, $1 is nothing and that's right until you read the documentation. $1 is used to define where to install the software.
if you say nothing it's nothing.
![Capture d’écran du 2022-07-20 13-20-17](https://user-images.githubusercontent.com/52078885/179969932-43d231b0-9230-41e2-ad64-650e90ce3bbd.png)

you have to say where to install it. if you don't it will install to /adobe-photoshop and yes that's the root folder.

**Comment by fislysandi** [comment]
oh then i just have to define $1 then and that would work?

**Comment by MiMillieuh** [comment]
> oh then i just have to define $1 then and that would work?
> 
> like this sh photoshop2022install.sh /path/to/your/install/folder? (taken from the github page)

Yeahy that's the thing. $1 is the first argument. so if you set it like in the example you mentioned it will work.

**Comment by fislysandi** [comment]
ye just thanks. sorry for attracting unneeded attention
