### ISSUE TITLE
scratch disk full

### ISSUE THREAD

**Issue by mycv1** [MiMillieuh/Photoshop-CC2022-Linux#51]
![1](https://user-images.githubusercontent.com/100340586/178933370-5f06bcbd-dd1f-41cf-a7ac-1bdb59a4c1c8.png)
**Photoshop version**
eg : CC2021

**Describe the bug**
photoshop not opening.

**To Reproduce**
started photoshop as usual, got the error "scratch disk full" and there was another disk below marked as "F" i selected it and it restarted photoshop and stuck at the photoshop boot screen (cloud, flamingo image)

**System informations**
- Distro : Debian11
- GPU : (NVIDIA)
![g](https://user-images.githubusercontent.com/100340586/178935115-bb93b0c4-d944-45d2-b677-e31702969fe9.png)

EDIT: Tried to open files (open with > photoshop) then its opened but unable to imp[ort  or drag drop psd files, scratch disks full error

**Comment by MiMillieuh** [comment]
You need to have a lot of free disk space... like on windows adobe cache takes your whole disk.

**Comment by MiMillieuh** [comment]
No further information.
