### ISSUE TITLE
exec: format error in the sh file

### ISSUE THREAD

**Issue by XDM-Inc** [MiMillieuh/Photoshop-CC2022-Linux#52]
not sure if typo or if other distros use this format(i run manjaro linux)  but the Photoshop installer script next to the bin folder in the header its a   "!#/bin/sh"  instead of the regular "#!/bin/sh the hash and exclamation point was swapped. switching it back fixed it (or just directly running the executable in the folder instead.

**Comment by MiMillieuh** [comment]
This issue occurred because you didn't used the last installer.
