### ISSUE TITLE
Photoshop takes up more space

### ISSUE THREAD

**Issue by mycv1** [MiMillieuh/Photoshop-CC2022-Linux#53]
**Photoshop version**
eg : CC2021

**Describe the bug**
The installation folder takes up more space (22gb)

**System informations**
- Distro : Debian11
- GPU : NVIDIA

**Additional context**
Help me to free up space by mentioning the folders that i can safely delete without breaking photoshop.
![1](https://user-images.githubusercontent.com/100340586/179164759-bf5b887b-a9e6-479a-997c-21e1f2fe69e5.png)

**Comment by MiMillieuh** [comment]
I don't know since mine does only 4.5GB...

**Comment by MiMillieuh** [comment]
Closed no further information
