### ISSUE TITLE
Can't start photoshop after install

### ISSUE THREAD

**Issue by Lekrixsss** [MiMillieuh/Photoshop-CC2022-Linux#54]
**Photoshop version**
CC2021

**Describe the bug**
Photoshop doesn't start

**To Reproduce**
1. do "sudo dnf install wine zenity tar wget curl"
2. download photoshop2021install.sh from latest releases 
3. do "sh ./photoshop2021install.sh ~/"
4. Start photoshop from app menu
5. Photoshop not start

**Expected behavior**
Photoshop work

**System informations**
- Distro : Fedora Linux 36
- GPU : Nvidia RTX 3060 Ti

**Additional context**
If run photoshop from Adobe-Photoshop/drive_c/launcher.sh get this output https://pastebin.com/TJygM8Kw

**Comment by MiMillieuh** [comment]
That's because you use wine-staging.

**Comment by Lekrixsss** [comment]
I use wine from "wine" fedora package? Is it contain wine-stagging?

**Comment by MiMillieuh** [comment]
Well in the logs you've sent it's mentioned wine-staging...
![image](https://user-images.githubusercontent.com/52078885/179292399-6ea087d0-0447-44c0-a338-283152ea4f1b.png)

**Comment by fislysandi** [comment]
mb try the AUR wine-stable package since it actually installs the stable version of wine and NOT the development version of it, official repos contain the wine dev as standart wine package, this doesnt make sense why wouldnt they just separate the wine to wine-stable and wine-dev?that would make more sense, want a stable expirience? use the wine-stable, feeling wanting to try something cutting edge and unstable? use wine-dev.

**Comment by fislysandi** [comment]
i dont reccomend to use yay for this since it makes the pkgbuild to fail so you have to clone it manually then
cd into it then
makepkg -si

and wait for it to compile

**Comment by Whax** [comment]
@fislysandi 

He is on Fedora, not arch linux ;) 

@Lekrixsss 

You should try this (I have no fedora under the hand so...I can't check but it should be fine)

```shell
sudo dnf remove 'wine*'
sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/36/winehq.repo
sudo dnf -y install wine-stable vulkan vulkan-info vulkan-tools
git clone https://github.com/MiMillieuh/Photoshop-CC2022-Linux
sh photoshop2022install.sh
```

**Comment by MiMillieuh** [comment]
> @fislysandi 
> 
> He is on Fedora, not arch linux ;) 
> 
> @Lekrixsss 
> 
> You should try this (I have no fedora under the hand so...I can't check but it should be fine)
> 
> ```shell
> sudo dnf remove 'wine*'
> sudo dnf -y install dnf-plugins-core
> sudo dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/36/winehq.repo
> sudo dnf -y install wine-stable vulkan vulkan-info vulkan-tools
> git clone https://github.com/MiMillieuh/Photoshop-CC2022-Linux
> sh photoshop2022install.sh
> ```
> 
> 
> 

That should be working.  However I would recommend to use the scripts in release instead of the master tree... 
Also be aware that 2022 isn't as functional and stable as 2021.

**Comment by Whax** [comment]
The default installer on main branch install the 2021 :p 
https://github.com/MiMillieuh/Photoshop-CC2022-Linux/blob/f2daea7b83beb1eb6f4fdb7d58a11e89d1bbf194/installer.sh#L22

**Comment by MiMillieuh** [comment]
Without further information,  I assume it's fixed.
