### ISSUE TITLE
Install script doesn't work properly on Artix (and maybe other Arch-based distros)

### ISSUE THREAD

**Issue by vproper** [MiMillieuh/Photoshop-CC2022-Linux#55]
Due to some differences, the script doesn't work properly on Arch-based distros. I'm providing a fixed install script (for CC 2021), hope that dev will see this fix

https://drive.google.com/file/d/1ITZvUZhw8I3dzxwgi7n_b1S6jFh3eWxG/view?usp=sharing - fixed script

**Comment by MiMillieuh** [comment]
Please read the read me instead of saying it's not working...
You have to use it with the dir after as an argument... 

ex : `sh installphotoshop2021.sh /home/user/adir/`

![image](https://user-images.githubusercontent.com/52078885/180283108-441ca759-dcac-441a-ad88-461374611bde.png)
