### ISSUE TITLE
Can't export image

### ISSUE THREAD

**Issue by 1nikolas** [MiMillieuh/Photoshop-CC2022-Linux#60]
**Photoshop version**
CC2021

**Describe the bug**
There is no way to export the image. Quick export as png opens no dialog and export as is empty (see screenshot bellow)

**To Reproduce**
1. Open and edit your image
2. Click "Quick export as png", nothing happens
3. Click "Export as...", nothing happens too

**Expected behavior**
Be able to export the image

**Screenshots**
The empty "Export As" dialog
![image](https://user-images.githubusercontent.com/30593419/188279575-0fa61b5b-d9d8-47c1-a8f4-d8a9bb8e5af0.png)

**System informations**
- Distro : ArchLinux
- GPU : Nvidia

**Additional context**
Just installed it

**Is some information are missing it might take longer to find the issue so please complete carefully**
Save As works fine. In fact I'm able to open the .psd on GIMP and export it. But what's the point in that?

**Comment by MiMillieuh** [comment]
Exporting doesn't work at all, you can save as png or jpeg with the save as tab. 
Or you can export with gimp. The point is even if you can't export using photoshop,  some people need all photoshop functionality or workflow.

I personally export using save as and choose png or jpeg.

I currently don't know how to fix it.

**Comment by 1nikolas** [comment]
Oh save as can save png.. Didn't notice

Funnily enough I remember myself trying to daily drive Ubuntu back in like 2016 and had the exact same problem on Photoshop. It seems there is no progress on that 😄

**Comment by MiMillieuh** [comment]
> Oh save as can save png.. Didn't notice
> 
> Funnily enough I remember myself trying to daily drive Ubuntu back in like 2016 and had the exact same problem on Photoshop. It seems there is no progress on that smile

Well I guess x) at least it still have a workaround to export.

**Comment by NeuHix** [comment]
Hey @MiMillieuh
You mentioned that you were [inspired](https://github.com/MiMillieuh/Photoshop-CC2022-Linux#special-thanks-to) by @Gictorbit
I'm trying to install Photoshop on linux for more than 5 days. So far, Only [this](https://github.com/Gictorbit/photoshopCClinux) repo has worked for me with anhttps://github.com/Gictorbit/photoshopCClinux/issues/177. And due to low data pack, I'm not currently able to install you repo's Photoshop. Can you please look into this issue . ? In your free time? Thanks!

**Comment by MiMillieuh** [comment]
> Hey @MiMillieuh
> You mentioned that you were [inspired](https://github.com/MiMillieuh/Photoshop-CC2022-Linux#special-thanks-to) by @Gictorbit
> I'm trying to install Photoshop on linux for more than 5 days. So far, Only [this](https://github.com/Gictorbit/photoshopCClinux) repo has worked for me with anhttps://github.com/Gictorbit/photoshopCClinux/issues/177. And due to low data pack, I'm not currently able to install you repo's Photoshop. Can you please look into this issue . ? In your free time? Thanks!

Is there anything to do with the issue of exporting ?

**Comment by NeuHix** [comment]
No. Its @Gictorbit's repo.  But maybe due to some work, he isn't active for a long time now.  Do you have an idea how it can be fixed? Please.

**Comment by MiMillieuh** [comment]
> No. Its @Gictorbit's repo.  But maybe due to some work, he isn't active for a long time now.  Do you have an idea how it can be fixed? Please.

I don't know... maybe if you use wine staging use the wine devel.

Maybe it's outdated. You should try on an older distro. 

To be clear I didn't take anything from his repo... just the concept of installing Photoshop. So I don't really know how his version works

**Comment by ikim23code** [comment]
For me, the Export function is working with wine-staging-7.5-1 and wine-staging-7.6-1.
