### ISSUE TITLE
Typo in `chmod+x`

### ISSUE THREAD

**Issue by ericek111** [MiMillieuh/Photoshop-CC2022-Linux#62]
Typo here, missing space in `chmod+x` :):
https://github.com/MiMillieuh/Photoshop-CC2022-Linux/blob/545dd1868f57b1d633fdd6fd7046392d00edb31c/scripts/photoshop2021install.sh#L69

fails with `photoshop2021install.sh: line 69: chmod+x: command not found`

**Comment by MiMillieuh** [comment]
Thanks for your report. 
it's fixed now.
