### ISSUE TITLE
Clone Stamp tool cannot be used : Could not use the clone stamp because the area to clone has not been defined

### ISSUE THREAD

**Issue by RainaMatthews** [MiMillieuh/Photoshop-CC2022-Linux#63]
**Photoshop version**
Version 2021

**Describe the bug**
when attempting to use the clone stamp tool, even when holding down ALT and selecting the source area, as soon as you click on another area to paint the source the error above appears

**To Reproduce**
1. create a new document, single layer, and paint a random swirl or anything anywhere.
2. select the Clone Stamp tool.  Hold down Alt (note the Cursor icon changes as it should) and click on the area you painted
3. release alt so cursor returns to normal, and click in a new area of the screen.  it SHOULD now paint in what was in the source area you clicked on when Alt was held down.

**Expected behavior**
it should paint in the cloned area of the image

**Screenshots**

**System informations**
- Distro : Mint 21 and 22
- GPU : Nvidia GTX 1650 ti

**Comment by MiMillieuh** [comment]
Hello, I'm sorry but I can't reproduce the issue you have... 

For me it's working like it would on Windows.

Are you up to date with wine ? Graphics driver ? 32bit library enabled since you're on a Ubuntu base ? 

Also I noticed a but in the installer a week ago on Ubuntu that I've patched but it isn't in the release section. [HERE](https://github.com/MiMillieuh/Photoshop-CC2022-Linux/tree/main/scripts) if you already used this folder to install it should already be fine.

I've tested on both Nvidia and AMD GPUs on Fedora 36

**Comment by RainaMatthews** [comment]
I did try the installer as you described and the same issue occurs.

I'm current running wine-7.17 (Staging)

and have the latest Nvidia 515.65.01-0ubuntu0.22.04.1

everything else is upto date as far as I'm aware.  everything else appears to work find in photoshop, just not clone stamp.

**Comment by MiMillieuh** [comment]
> I did try the installer as you described and the same issue occurs.
> 
> I'm current running wine-7.17 (Staging)
> 
> and have the latest Nvidia 515.65.01-0ubuntu0.22.04.1
> 
> everything else is upto date as far as I'm aware.  everything else appears to work find in photoshop, just not clone stamp.  

Maybe the issue is wine staging...
I know there are some issues with staging patches and photoshop.  Maybe you shoukd try with a vanilla wine devel.

**Comment by RainaMatthews** [comment]
ok figured it out .

seems that on Mint, Alt+Left Click is setup to allow for window dragging.

https://forums.linuxmint.com/viewtopic.php?t=264172
details how to change it to some other key combination, and this resolved the issue for me

**Comment by MiMillieuh** [comment]
> ok figured it out .
> 
> seems that on Mint, Alt+Left Click is setup to allow for window dragging.
> 
> https://forums.linuxmint.com/viewtopic.php?t=264172 details how to change it to some other key combination, and this resolved the issue for me

It's not related to your distro usually... it's more the DE. Maybe you could tell the DE you're using so anyone else with this issue will know what to do ?
