### ISSUE TITLE
[CC2022] Wine C++ Runtime Library Error

### ISSUE THREAD

**Issue by RealShiroTheNerd** [MiMillieuh/Photoshop-CC2022-Linux#64]
**Photoshop version**
CC2022

**Describe the bug**
As soon as I create a project and try doing anything, the whole programs crashes.

**To Reproduce**
Create a new project and try to do literally anything

**Expected behavior**
For it not to crash ig?

**Screenshots**
![image](https://user-images.githubusercontent.com/61495410/190454514-f3fe9ceb-7593-48b1-9f3f-9924e835f083.png)

**System informations**
- Distro : Ubuntu 22
- GPU : NVIDIA Geforce RTX 2070S

**Comment by MiMillieuh** [comment]
CC 2022 is really unstable as I said.

I don't really give support to that version. but it works in certain conditions.

You should try to install some VCredist in the prefix
