### ISSUE TITLE
[CC2021] The view does not refresh (after undoing changes)

### ISSUE THREAD

**Issue by SlidyDev** [MiMillieuh/Photoshop-CC2022-Linux#65]
**Photoshop version**
CC2021

**Describe the bug**
The view does not refresh after undoing changes. You have to move/zoom for it to actually refresh and show the undone changes

**System informations**
- Distro : Ubuntu 22
- GPU : NVIDIA Gefore RTX 2070S

**Comment by MiMillieuh** [comment]
What is your wine version ?

**Comment by SlidyDev** [comment]
wine-7.17

**Comment by MiMillieuh** [comment]
OK well if it's not staging it should be fine... are your GPU driver installed correctly ? (NVIDIA PROPRIETARY)

And since you're on Ubuntu, have you tried the installer in the scripts folder or the release one ? Because the mainline contains a little fix for ubuntu

**Comment by SlidyDev** [comment]
I think so, but I will check when I have time

**Comment by SlidyDev** [comment]
This is the driver I currently have
![image](https://user-images.githubusercontent.com/61495410/191806471-3186a988-65bc-4805-a7f4-b2edd57417f5.png)

**Comment by ktonini** [comment]
I had this same issue on Pop OS, using the release script.  Can confirm using the mainline script has fixed it for me so far.

**Comment by MiMillieuh** [comment]
Closed for inactivity and maybe fixed  ?

**Comment by RealShiroTheNerd** [comment]
Sorry, I stopped using linux. I give up
