### ISSUE TITLE
[CC2021] Pen pressure support

### ISSUE THREAD

**Issue by TheSunCat** [MiMillieuh/Photoshop-CC2022-Linux#67]
Photoshop version: CC2021

**Describe the bug**
This script works great, however it seems pen pressure is not recognized by Photoshop. When enabling the option, it shows a warning icon saying "Control by pen pressure requires the use of a pressure sensitive tablet". I'm using an XP-PEN Deco01V2 tablet, with OpenTabletDriver, and have checked that pressure works in other apps such as Krita.

**To Reproduce**
1. Plug in a drawing tablet and ensure pressure is working (using OpenTabletDriver, for example)
2. Launch Photoshop installed with this script
3. Open the Brush Settings window, and change the Control setting for Shape Dynamics to Pen Pressure. 
4. Observe the warning icon, and that brushes do not react to pen pressure.

**Expected behavior**
Ability to use pen pressure in Photoshop.

**Screenshots**
![image](https://user-images.githubusercontent.com/44881120/191747215-7325e37b-73e3-4321-b41c-f744406ee1a3.png)

**System information**
- Distro: Arch Linux
- GPU: AMD
- WINE version: `wine-7.17 (Staging)`

**Additional context**
This might be related to [this](https://bugs.winehq.org/show_bug.cgi?id=18517) WINE issue, which says it is in "STAGING". However, I am using `wine-staging` and pressure still does not work, so I'm unsure.

**Comment by MiMillieuh** [comment]
This is wine related... I can't really do anything about it sadly...

Wine don't currently support pressure. in fact wine take touch screen as a mouse

Maybe Krita can be your answer in that case.

If I fin a way I'll update it but I'm not really optimist about that one.

**Comment by TheSunCat** [comment]
Thanks for the quick response! Do you think anything can be done to help the WINE issue be resolved? I have yet to get one of the patches sent on that bug report working, and it hasn't had activity (that I can find) for two years. I would be happy to try debug this myself if there is currently no solution, but I'm afraid of wasting maintainers' time.

**Comment by MiMillieuh** [comment]
Well you can also patch wine by yourself if you find something interesting about that. and if it's a working feature it's not wasting maintainers time.

if you have a patch you just need to build wine by yourself with the patch but they can break on some wine updates
