### ISSUE TITLE
Camera RAW gets greyed out afer a while

### ISSUE THREAD

**Issue by nicks-boson** [MiMillieuh/Photoshop-CC2022-Linux#68]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
eg : CC2021

**Describe the bug**

**To Reproduce**
1. Go to '.Camera RAW'
2. Click on 'Play with some settings'
3. After a while it greys out. But when I alt-tab back and forth it comes back for a couple of seconds

**Expected behavior**
Of course I expect to be able and just use camera raw. It doesn't matter if I use a 8 or 16 bit image

**Screenshots**

**System informations**
- Distro : Ubuntu 22.04.1
- GPU : 2x RTX 3090
- WINE version : 7.1

**Additional context**
I can make screen recording if needed

**Is some information are missing it might take longer to find the issue so please complete carefully**

**Comment by MiMillieuh** [comment]
Your answer is right here...

https://github.com/MiMillieuh/Photoshop-CC2022-Linux/releases/tag/2.1.1
