### ISSUE TITLE
App not started after installation

### ISSUE THREAD

**Issue by baraakhateeb** [MiMillieuh/Photoshop-CC2022-Linux#80]
➜  scripts git:(main) ✗ ./launcher.sh
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

photoshop.exe not exist at all.

**Comment by MiMillieuh** [comment]
Did you at least read how to install it ?

Because you're in MAIN witch means that you've cloned it and launched launcher.sh assuming it was already installed ? 

You need to run the installer in scripts before

**Comment by baraakhateeb** [comment]
> Did you at least read how to install it ?
> 
> Because you're in MAIN witch means that you've cloned it and launched launcher.sh assuming it was already installed ?
> 
> You need to run the installer in scripts before

Yes i did , photoshop files after installation :
![Screenshot_20221120_173040](https://user-images.githubusercontent.com/54423291/202908016-b21a4574-dbc1-4faa-866b-d36c87bf576f.png)

**Comment by MiMillieuh** [comment]
Well I don't know then, maybe you could share more logs about the installation?

**Comment by MiMillieuh** [comment]
Closed for inactivity
