### ISSUE TITLE
Can't open after installation CC2021 (CLI and GUI both tested)

### ISSUE THREAD

**Issue by Shanespeed** [MiMillieuh/Photoshop-CC2022-Linux#81]
Version:
Photoshop CC2021

Bug:
The installation works well. However I can't open the application at all, doesn't give any feedback on why at first glance. Trying to run the launcher.sh (located at Adobe-Photoshop/drive_c/launcher.sh) with terminal nets an error which might be what we're looking for. Not sure if it matters but it closes quite quickly.
I tried it using both the CLI and the GUI version, same results.

Error in terminal when running launcher.sh:
```
0024:err:module:import_dll Library d3d12.dll (which is needed by L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\photoshop.exe") not found
0024:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\photoshop.exe" failed, status c0000135
```

Extra info:
I am not familiar with Linux at all, this is my 2nd day using it. It looks like a DirectX 12 DLL is missing? At least that's what I can grasp from it. How would I even go about fixing that?
I also looked at the other issues but I can't find my answer in it.

System information:
- Distro : Zorin OS 16.2
- WINE version : 7.0.1 (I chose the Ubuntu version which matched the one Zorin 16.2 is built on)
- GPU : Nvidia RTX 2070
- CPU : Ryzen 7 2700x
- Storage type : Sata SSD

Thank you for your time making it and hopefully helping me!

**Comment by MiMillieuh** [comment]
Hello, 

First the GUI version isn't maintained anymore.

Secondly,  I'll have to ask you if you use the proprietary Nvidia driver, (nvidia-current I think on Ubuntu based)

And I would recommend to install wine with the official repository and also I recommend using wine-devel

Just go on winehq website and copy and paste instructions for Ubuntu.

**Comment by Shanespeed** [comment]
Hi there!

My latest install was with the CLI (again) so that should be no issue.

I am using the Nvidia version 520 proprietary drivers.

I updated my Wine (using instructions from winehq) after figuring out it didn't work first time. I updated it to the 7.0.1 stable branch. I'll test out the development branch after work. I assume I need to uninstall the current wine version first?

**Comment by MiMillieuh** [comment]
Well if you still have wine from Ubuntu repository you might not be able to install it.

Maybe you could try to launch it with a wine bin but I think it's a dependencies issue and winehq repository have those dependencies

**Comment by Shanespeed** [comment]
Alright so I found that under an app called "configure wine" the Windows version was set to Windows 7. Windows 7 doesn't support DirectX 12 as far as I am aware. After setting it to Windows 10 it opened! However it doesn't work despite finally opening. It nets me 2 different errors that aren't in the terminal (as far as I am aware).

![Screenshot from 2022-12-01 20-09-22](https://user-images.githubusercontent.com/22288471/205139006-f23a5ed1-784a-4962-b65c-3fe2437a7ca5.png)

Would you like for me to open a new issue for this? Or would you like to continue here?

**Comment by MiMillieuh** [comment]
It's not necessary to open a new issue. 

But since the wine prefix has been a bit messed up in win7 mode, I would recommend to fresh install again the script.

**Comment by Shanespeed** [comment]
I'll try it after work.

Also, maybe a stupid question, but is uninstalling in Linux really just a matter of deleting the files/folders? No uninstallers or hidden places I have to check?

**Comment by MiMillieuh** [comment]
It should just be in your install folder,

The icon is also stored in $HOME/.local/share/icon but you don't need to delete it.

You might need to delete the desktop file.

$HOME/.local/share/application/photoshop.desktop

**Comment by Shanespeed** [comment]
Alrighty, I do understand the uninstallation process in that case. I'll update you on the situation after work!

**Comment by Shanespeed** [comment]
I reinstalled it after installing the devel branch for Ubuntu 20.04. Wine 7.22 is the current version.

It installed without issues and opened without issues. It seems to work fine without any artifacts or errors now!
Thank you so much!
