### ISSUE TITLE
Missing DLL d3d12.dll on Photoshop 2021

### ISSUE THREAD

**Issue by CHJ85** [MiMillieuh/Photoshop-CC2022-Linux#82]
Hi there. I just installed PS 2021. The application is not able to launch due to missing file "d3d12.dll".
```
0024:err:module:import_dll Library d3d12.dll (which is needed by L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\photoshop.exe") not found
0024:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\photoshop.exe" failed, status c0000135

```
I downloaded the missing file. And now, I'm getting this error:
`00fc:err:sync:RtlpWaitForCriticalSection section 0000000170065600 "dlls/ntdll/loader.c: loader_section" wait timed out in thread 00fc, blocked by 0024, retrying (60 sec)`

Not sure what that is about

I'm using Wine version 7.0.1.

**Comment by MiMillieuh** [comment]
Hello,

May I know your CPU GPU and OS ? 

Those are crucial information I need.

But according your wine version,  I suppose you're on Ubuntu without wineHQ repos

**Comment by MiMillieuh** [comment]
Can you try with the wine-devel packages ?

I noticed that Ubuntu users are getting that kind of issue since a few days... 

Maybe there were some changes in Ubuntu repository.

Also if it doesn't work can you check with winecfg if the version is windows 10 ?

The dll you installed won't work since it's an official one I guess. This installer use Proton-VKD3D. And DXVK.

**Comment by CHJ85** [comment]
Okay so I'll remove the dll again.
Btw. Not sure if it matters. But since you asked. My CPU Is Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by MiMillieuh** [comment]
Well since you might have messed up some settings I would recommend to fresh install photoshop.

But before if you can check the winecfg prefix and look at the windows version. 

The CPU isn't that important in that case. I ask it in case of integrated GPU usage.

**Comment by CHJ85** [comment]
I finally got it working, on the devil version 7.22.
Thanks for your help.

**Comment by MiMillieuh** [comment]
> I finally got it working, on the devil version 7.22.
> Thanks for your help.

So it's related to the stable version of wine.

**Comment by CHJ85** [comment]
Yup, it seems that way.
