### ISSUE TITLE
On Extracting redist stage of Installation (70%) its just stops and keeps hanging at this stage

### ISSUE THREAD

**Issue by 1VinuR1** [MiMillieuh/Photoshop-CC2022-Linux#87]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
CC2021

**Describe the bug**
On Extracting redist stage of Installation (70%) its just stops and keeps hanging at this stage

**To Reproduce**
Just run installation on manjaro

**Expected behavior**
I wanted to install Photoshop CC2021

**Screenshots**
![ps issue](https://user-images.githubusercontent.com/122370850/211873758-8f2990d2-2f05-4bec-a635-e832ff17da8a.png)

**System informations**
- Distro : Manjaro Linux 22.0
- GPU : AMD Radeon RX 6600 (non-XT)
- WINE version : 7.22

**Additional context**

**Comment by MiMillieuh** [comment]
You should know if you've readed the README.md that the GUI installer is deprecated and will not work anymore.

Please try using the CLI installer as explained in the README.md

**Comment by 1VinuR1** [comment]
Ok, thanks!
