### ISSUE TITLE
Suggestion: Use Proton and dxvk

### ISSUE THREAD

**Issue by hellkaim** [MiMillieuh/Photoshop-CC2022-Linux#93]
I recently came across lutris and foud out there is a standalone proton enabled wine build called [Proton-GE](https://github.com/GloriousEggroll/proton-ge-custom). Also there is  a [dxvk](https://github.com/doitsujin/dxvk) but is currently only support Direct3d 11, not 12 (as required by PS.

Have you played with that?

**Comment by MiMillieuh** [comment]
Hello, I've already experimented these two things, Proton makes Photoshop window invisible and DXVK is already provided
