### ISSUE TITLE
Photoshop stops working after the first successful launch

### ISSUE THREAD

**Issue by Smirnaff** [MiMillieuh/Photoshop-CC2022-Linux#94]
**Photoshop version**
CC2021

**Describe the bug**
After the clean install with latest Winehq-stable, latest Nvidia drivers and latest script the first launch goes completely normally after automatic ~/.wine configuration (both either with iGPU or dGPU). The next attempts to launch Photoshop with either iGPU or dGPU don't work. When trying to launch from terminal it says:
`0178:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0178:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
`
and
`01a0:err:vulkan:init_vulkan Failed to load Wine graphics driver supporting Vulkan.
`
Full log of what's happening is below.
But if I delete ~/.wine folder and run it again, it works fine again, but only the first time.

**To Reproduce**
1. Install winehq-stable and Photoshop using this script
2. Launch Photoshop either through Terminal or with an icon, either with iGPU or dGPU
3. Wait for it to load normally
4. Close it
5. Launch photoshop again
6. See system lagging and nothing happening or aforementioned errors in the Terminal if launched through it

**Expected behavior**
Photoshop launching properly every time with either iGPU or dGPU

**System informations**
- Distro : Pop!_OS 22.04
- GPU : Intel HD Graphics 630 + NVIDIA GeForce GTX 1050 Mobile (Driver 525.85.05)
- WINE version : winehq-stable 8.0

**Additional context**
Actually, I'm not sure if this is the bug with this script and software, since it used to work just fine before the latest minor Nvidia driver update and Winehq update. But maybe they've changed something that works differently now and can be fixed by updating something here for the new versions. 
My temporal solution is to modify launcher.sh so it deletes ~/.wine folder every launch, but it's obviously not an ideal slow workaround.

**Full terminal log**
`smirnaff@pop-os:~$ bash -c "/home/smirnaff/Photoshop/Adobe-Photoshop/drive_c/launcher.sh %F"
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F2D0 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F000 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F560 1 C) semi-stub
0024:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\dvacrashhandler.dll", 000000000BB47970) stub
0024:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0024:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0024:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0024:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FC10 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FC80 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FCD0 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FCD0 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FCD0 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E8C0 1 C) semi-stub
00e8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00e8:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
00ec:fixme:win:DisableProcessWindowsGhosting : stub
00e4:fixme:reg:RegQueryInfoKeyW security argument not supported.
00e4:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EFF0 1 C) semi-stub
00fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0063F63C 1 C) semi-stub
00fc:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0063F53C 1 C) semi-stub
0104:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0104:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0154:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E010 1 C) semi-stub
0154:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DED0 1 C) semi-stub
0154:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0154:fixme:wbemprox:client_security_SetBlanket 00000001ED4A0E40, 0000000000B92EC0, 10, 0, (null), 3, 3, 0000000000000000, 0
0154:fixme:wbemprox:client_security_Release 00000001ED4A0E40
0154:err:vulkan:init_vulkan Failed to load Wine graphics driver supporting Vulkan.
0154:err:vulkan:init_vulkan Failed to load Wine graphics driver supporting Vulkan.
0154:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DDB0 1 C) semi-stub
0154:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DB80 1 C) semi-stub
0154:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DAE0 1 C) semi-stub
0154:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithDataSegs
0154:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithHandleData
0154:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpFilterMemory
0154:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DF10 1 *) semi-stub
0024:fixme:seh:WerUnregisterRuntimeExceptionModule (L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\CRClient.dll", 00000000024E1050) stub
smirnaff@pop-os:~$ 
`

**Comment by Smirnaff** [comment]
> Hello, could you please try to use wine-devel instead of wine-stable, I noticed that a lot of issues came from wine-stable so maybe that's the case (after installing it please reinstall photoshop) Let me know if it works.

I used to use winehq-devel 8.0 before it got updated to 8.1, but after the update when I try to use it and launch Photoshop, it gives the error that the unsupported version of Windows 10 is used. So I had to go to winehq-stable 8.0, since it doesn't show this error on 8.0

**Comment by MiMillieuh** [comment]
That's weird, I have wine 8.1 and I don't encounter that issue.
The issue you encounter in your 8.0 try is vulkan related, do you have vulkan installed ? try installing vulkan-tools and run vkcube to know if it's working fine.

**Comment by Smirnaff** [comment]
I have vulkan installed and vkcube works okay. And as I said, at the first launch it recognizes Vulkan and launches and works perfectly. Something breaks only on the nect attemts. 
My games work fine too, except for Steam ones with Proton, that's why I think there's probably something wrong with Nvidia drivers update which broke everything. Hovewer, if I launch Steam games with my regular winehq (the same one I use for Photoshop) and on different prefix, they work just fine. Before the Nvidia drivers update all games, including Steam ones, and Photoshop, worked completely flawless.
All I mean by that, is that Vulkan seems to work okay, but strange. I tried to google and fix my Steam games issue, but had no luck. I've seen suggestions to revert back to some older Nvidia drivers, but haven't tried this yet. But on the other hand, this bug with Photoshop and games persists for me even when I use Intel GPU, so I'm really out of ideas, why's that the case.

**Comment by MiMillieuh** [comment]
So maybe an update of Vulkan shipped with the driver is the cause...

If that's a driver issue, it's nothing I can really do to be honest but ill try at home to updates my Nvidia drivers.

**Comment by MiMillieuh** [comment]
So maybe an update of Vulkan shipped with the driver is the cause...

If that's a driver issue, it's nothing I can really do to be honest but ill try at home to updates my Nvidia drivers.

**Comment by Smirnaff** [comment]
Okay, thank you for your efforts!

**Comment by MiMillieuh** [comment]
After trying on my machine, it still works on my system... 

I don't really know what cause the issue on your system, maybe it's a Ubuntu related one since you're on Pop OS

**Comment by Smirnaff** [comment]
Well, anyway, thank you for trying! At least now I can be sure that this software is fine and the issue is somewhere else

**Comment by MiMillieuh** [comment]
> Well, anyway, thank you for trying! At least now I can be sure that this software is fine and the issue is somewhere else

Sorry that I can't help you further, Feel free to open this issue again if the issue persist and everything else work.

**Comment by RJM3054** [comment]
I just went through the same issue  in openSUSE 15.4 with a amd RX580. I am using the KDE dekstop and like you after installation it will open one or two times then stop. After checking mine it resulted that the culprit was the thickness of the taskbar which I move to the top and use a dock on the bottom. If the bar was to thin I will have the bug where Photoshop doesn't render. After making it a bit thicker it will work. I did this a couple of times and the pattern was the same. So it may not be your case but the problem may have something to do with the desktop setup. Good luck.

**Comment by Smirnaff** [comment]
That's an interesting story, but unfortunately you're right, in my case the issue is with something else. I didn't change anything with my desktop setup when that happened

**Comment by MiMillieuh** [comment]
By the way I can confirm that the latest nvidia driver causes issue with some vulkan apps (I have some issues with some games but photoshop launch fine) Let's hope it will be fixed soon...

**Comment by Smirnaff** [comment]
Ok, got it, thank you for the info!

**Comment by Smirnaff** [comment]
Quick update. I downgraded the Nvidia driver to 515 and now everything works fine again, Photoshop and even Steam games. Therefore I can conclude that Nvidia f-ed up again, classic

**Comment by MiMillieuh** [comment]
Another update, The wrong windows version issue is caused by wine 8.0+ it's fixable by removing wine, installing an older version (I've tried with 7.22) then installing Photoshop, launch it once and then you can reinstall the latest wine.

**Comment by Smirnaff** [comment]
And another update, for some reason this error still exists on the older driver, It was too soon to celebrate. I worked right after installation, and continued to work later, but after some time the same error appeared again. Maybe I should try to use older wine 7.22...

**Comment by MiMillieuh** [comment]
> And another update, for some reason this error still exists on the older driver, It was too soon to celebrate. I worked right after installation, and continued to work later, but after some time the same error appeared again. Maybe I should try to use older wine 7.22...

Maybe the drivers are an issue on the ubuntu side but I'm using the Nvidia driver 525.89.02 and it works well for now. I guess that's even worst and that's a double issue on the ubuntu side. or I don't know, but if downgrading your driver works keep going with that until it's fixed.

**Comment by Smirnaff** [comment]
Yeah maybe the issue is on Ubuntu's or Pop!_OS's side, but the whole reason I installed Pop!_OS is that people said there are no issues with graphics...

**Comment by MiMillieuh** [comment]
> Yeah maybe the issue is on Ubuntu's or Pop!_OS's side, but the whole reason I installed Pop!_OS is that people said there are no issues with graphics...

Well sometimes it can have some issue... PopOS uses the graphic PPA like ubuntu it's just pre installed and so when you install your os you're ready to go, that's why it's usually recommended with Nvidia GPUS

**Comment by Smirnaff** [comment]
Btw, can I ask, why does it use default ~/.wine prefix? I thought it should've been using the prefix located on the folder I've chosen to install Photoshop into

**Comment by MiMillieuh** [comment]
> Btw, can I ask, why does it use default ~/.wine prefix? I thought it should've been using the prefix located on the folder I've chosen to install Photoshop into

It's not using the .wine prefix, but if an update is needed, it will update the base prefix and the ps prefix at the same time, if it was using the .wine prefix, it won't even start.

**Comment by Smirnaff** [comment]
Okay thank you. I've made this assumption, because when I start Photoshop for the first time it creates .wine prefix, and as I mentioned earlier the issue I'm having can be bypassed by deleting said .wine prefix. That means, I assume, that it somehow affects the installation

**Comment by Smirnaff** [comment]
I temporarily fixed the issue by blocking the access to .wine prefix by removing permissions. Now Photoshop launches fine everytime. I have no idea how this works, but here we are

**Comment by ikim23code** [comment]
If you're a Linux newbie like me and don't know how to downgrade Wine, check this out:

https://forum.winehq.org/viewtopic.php?f=8&t=34234

**Comment by intheworlditsgone** [comment]
> Another update, The wrong windows version issue is caused by wine 8.0+ it's fixable by removing wine, installing an older version (I've tried with 7.22) then installing Photoshop, launch it once and then you can reinstall the latest wine.

You can't downgrade Wine on ubuntu

**Comment by MiMillieuh** [comment]
> > Another update, The wrong windows version issue is caused by wine 8.0+ it's fixable by removing wine, installing an older version (I've tried with 7.22) then installing Photoshop, launch it once and then you can reinstall the latest wine.
> 
> You can't downgrade Wine on ubuntu

https://askubuntu.com/questions/139405/how-to-downgrade-wine

**Comment by millionsofplayers** [comment]
> > > Another update, The wrong windows version issue is caused by wine 8.0+ it's fixable by removing wine, installing an older version (I've tried with 7.22) then installing Photoshop, launch it once and then you can reinstall the latest wine.
> > 
> > 
> > You can't downgrade Wine on ubuntu
> 
> https://askubuntu.com/questions/139405/how-to-downgrade-wine

this just doesn't work
