### ISSUE TITLE
load_gdiplus fails

### ISSUE THREAD

**Issue by seaofrandomness** [MiMillieuh/Photoshop-CC2022-Linux#97]
Executing load_fontsmooth rgb
Setting font smoothing to rgb
Executing wine C:\windows\syswow64\regedit.exe C:\windows\Temp\fontsmooth.reg
Executing wine64 C:\windows\regedit.exe C:\windows\Temp\fontsmooth.reg
Executing w_do_call gdiplus

warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

Executing load_gdiplus
grep: warning: stray \ before /
Executing cabextract -q -d /home/ghosty/cc21//Adobe-Photoshop/dosdevices/c:/windows/temp -L -F x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll /home/ghosty/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
/home/ghosty/cc21//Adobe-Photoshop/dosdevices/c:/windows/temp/x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll: No such file or directory

warning: Note: command cabextract -q -d /home/ghosty/cc21//Adobe-Photoshop/dosdevices/c:/windows/temp -L -F x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll /home/ghosty/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe returned status 1. Aborting.

**Comment by MiMillieuh** [comment]
Any context ? 

When you open an issue you need to answer some questions... I can't really help you without these.

**Comment by MiMillieuh** [comment]
I'm closing it due to lack of activity and not knowing what the issue cause...
